name: integration

on: [push, pull_request, workflow_dispatch]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8

    steps:
    - name: Set up Python 3.11 x64
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: x64

    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Test
      run: pytest -n 4
